### ISSUE TITLE
script should not use ActiveObject

### ISSUE THREAD

**Issue by 5263** [jreinhardt/CADinet-freecad#1]
Traceback (most recent call last):
  File "cadinet.FCMacro", line 93, in <module>
    if doc.ActiveObject.isDerivedFrom("Part::Feature"):
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'isDerivedFrom'

It might not be present. 
It might not be the top level object.

**Comment by jreinhardt** [comment]
Ok.

Is there a reliable way to determine the right object? Probably user selection. Or can one use the dependency tree to find a top level object?
